Fix inappropriate value for attribute
Error: Incorrect attribute value type

  on .terraform/modules/vpc_es_cleanup/lambda.tf line 40, in resource "aws_lambda_function" "es_cleanup":
  40:     subnet_ids         = ["${var.subnet_ids}"]

Inappropriate value for attribute "subnet_ids": element 0: string required.


Error: Incorrect attribute value type

  on .terraform/modules/vpc_es_cleanup/lambda.tf line 41, in resource "aws_lambda_function" "es_cleanup":
  41:     security_group_ids = ["${compact(concat(local.sg_ids, var.security_group_ids))}"]

Inappropriate value for attribute "security_group_ids": element 0: string
required.